### ISSUE TITLE
macOS: Cert error breaks :update

### ISSUE THREAD

**Issue by jeremy-w** [saif-ellafi/play-by-the-writing#13]
[Reported in Discord](https://discord.com/channels/1204536076157456444/1204705643987075072/1230272973248790640):

`:update` seems to be triggering an SSL exception (SSL: CERTIFICATE_VERIFY_FAILED)

```
[89034] Failed to execute script 'playbtw_core' due to unhandled exception: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1006)>
    [89034] Traceback:
    Traceback (most recent call last):
      File "urllib/request.py", line 1348, in do_open
      File "http/client.py", line 1294, in request
      File "http/client.py", line 1340, in _send_request
      File "http/client.py", line 1289, in endheaders
      File "http/client.py", line 1048, in _send_output
      File "http/client.py", line 986, in send
      File "http/client.py", line 1466, in connect
      File "ssl.py", line 517, in wrap_socket
      File "ssl.py", line 1108, in _create
      File "ssl.py", line 1383, in do_handshake
    ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1006)
    
    During handling of the above exception, another exception occurred:
```

Confirmed not on a corporate network. Issue reproduces on residential wifi and phone hotspot. Suspect requests is not looking for cert.pem in the right place.

**Comment by jeremy-w** [comment]
this didn't repro for me. but I'll have to verify I'm in fact running the latest version and not an earlier one to be sure.

**Comment by saif-ellafi** [comment]
need one more case, or figure out a way to reproduce

**Comment by jeremy-w** [comment]
Yeah. Maybe could do a screen share via Discord at some point to debug in the failing environment.
